include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    annotate_overrides: ignore
    constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_const_constructors_in_immutables: ignore
    unnecessary_this: ignore
    use_build_context_synchronously: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
